# frozen_string_literal: true

source 'https://rubygems.org'

# This is the default theme for new Jekyll sites.
gem 'minima', '~> 2.5'

group :jekyll_plugins do
  gem 'github-pages'
  gem 'jekyll-feed', '~> 0.12'
end
